app = "aicards-mint"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  SUI_BIN = "sui"
  AICARDS_PACKAGE_ID = "0x848b7e822fc93e05212d0002287d079d3cb5ef7fe0be1458091496aaf2aa95d2"
  AICARDS_ADMIN_CAP_ID = "0xb8fca933e7198d496f75027f6a0d3189dcd3651205a5f6f590ee2571837cada3"
  AICARDS_IMAGE_URL = "https://aicards.fun/cards"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
